import Head from 'next/head'
import { use, useEffect, useRef, useState } from 'react'
import Comp1 from "../components/comp1"
import Comp2 from "../components/comp2"
import Comp3 from "../components/comp3"
import Comp4 from "../components/comp4"
import Navbar from "../components/navbar"
import Footer from "../components/footer"
import Hero from "../components/hero"


export default function Home() {

  const modelRef = useRef()
  const [model,setModel] = useState("google-negative-300")

  useEffect(()=>{
    console.log(model)
  },[model])

  return (
    <>
      <Head>
        <title>Word2Vec</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center">

        <Navbar />
        <Hero />
        <div className="w-[90%] flex flex-col gap-6 justify-center">
          <h2 className="text-4xl font-bold text-center">Tasks</h2>
          <div className='w-full'>
            <select onChange={(e)=>setModel(e.target.value)} ref={modelRef} className='w-full p-2 border-2 rounded-lg'>
              <option value="google-negative-300">GoogleNews-vectors-negative300</option>
              <option value="wiki-hindi">wiki.hindi</option>
            </select>
          </div>
          <div className="grid lg:grid-cols-2 grid-cols-1 gap-8">
            <Comp1 model={model} />
            <Comp2 model={model} />
            <Comp4 model={model} />
            <Comp3 model={model} />
          </div>
        </div>

        <Footer />
      </main>
    </>
  )
}
